const DATA_KEY="ssg_data_v1";
const uid=()=>JSON.parse(localStorage.getItem(USER_KEY)||"{}").id||"guest";
const defaultData={profile:{name:"",id:"SG001",dob:"",mobile:"",address:"Hasanpur, Bihar",bank:"State Bank of India",account:"",ifsc:"",holder:"",join:"2025-01-01",designation:"Security Guard",site:"SSD Farm Hasanpur",shift:"Night",salary:15500},settings:{hours:12,auto:12,break:30},attendance:{},round:{name:"Night Round",target:4,done:0},punch:{in:null,out:null,last:null}};
let data=JSON.parse(localStorage.getItem(DATA_KEY+"_"+uid())||"null")||structuredClone(defaultData);
function save(){localStorage.setItem(DATA_KEY+"_"+uid(),JSON.stringify(data))}
function toast(t){const x=document.getElementById("toast");x.textContent=t;x.classList.add("show");setTimeout(()=>x.classList.remove("show"),1800)}
function todayKey(d=new Date()){return d.toISOString().slice(0,10)}
function fmtDate(d){return d.toLocaleDateString("en-IN",{day:"2-digit",month:"short",year:"numeric"})}
function money(n){return "₹"+Number(n||0).toLocaleString("en-IN",{minimumFractionDigits:2,maximumFractionDigits:2})}
function showPage(id){
  document.querySelectorAll(".page").forEach(p=>p.classList.toggle("active",p.id===id));
  document.querySelectorAll(".nav-btn").forEach(b=>b.classList.toggle("active",b.dataset.page===id));
  if(id==="attendance")renderAttendance(); if(id==="salary")renderSalary(); if(id==="reports")renderReport(); if(id==="profile")renderProfile(); if(id==="patrol")renderPatrol();
}
document.querySelectorAll(".nav-btn").forEach(b=>b.onclick=()=>showPage(b.dataset.page));
function init(){
 if(!getAuth()){document.getElementById("authScreen").classList.remove("hidden");document.getElementById("app").classList.add("hidden");return}
 document.getElementById("authScreen").classList.add("hidden");document.getElementById("app").classList.remove("hidden");
 const now=new Date(); document.getElementById("todayText").textContent=fmtDate(now);
 document.getElementById("bigDate").textContent=now.toLocaleDateString("en-IN",{day:"2-digit",month:"short",year:"numeric"});
 document.getElementById("dayName").textContent=now.toLocaleDateString("en-IN",{weekday:"long"});
 document.querySelectorAll('input[name="shift"]').forEach(r=>{r.checked=r.value===data.profile.shift.toLowerCase();r.onchange=()=>{data.profile.shift=r.value==="night"?"Night":"Day";save();updateShift()}});
 document.getElementById("siteInput").value=data.profile.site;
 document.getElementById("siteInput").onchange=e=>{data.profile.site=e.target.value;save()};
 updateShift();renderPunch();renderProfile();renderSettings();renderReport();
 document.getElementById("punchIn").onclick=punchIn;document.getElementById("punchOut").onclick=punchOut;
 document.getElementById("patrolBtn").onclick=()=>showPage("patrol");
 document.getElementById("saveRound").onclick=()=>{data.round.name=document.getElementById("roundName").value;data.round.target=Math.max(1,+document.getElementById("roundTarget").value||1);data.round.done=0;save();renderPatrol();toast("Round saved")};
 document.getElementById("completeRound").onclick=()=>{if(data.profile.shift!=="Night")return toast("Patrol is available only on night shift");if(data.round.done<data.round.target){data.round.done++;save();renderPatrol();document.getElementById("roundCount").textContent=`${data.round.done} / ${data.round.target}`;toast("Round completed")}};
 document.getElementById("saveProfile").onclick=saveProfile;
 document.getElementById("printSalary").onclick=()=>window.print();
 document.getElementById("whatsappBtn").onclick=()=>{const t=encodeURIComponent(document.getElementById("reportText").value);window.open("https://wa.me/?text="+t,"_blank")};
 document.getElementById("exportBtn").onclick=exportData;document.getElementById("importBtn").onclick=()=>document.getElementById("importFile").click();document.getElementById("importFile").onchange=importData;
 document.getElementById("resetBtn").onclick=()=>{if(confirm("Reset all app data?")){localStorage.removeItem(DATA_KEY+"_"+uid());location.reload()}};
 document.getElementById("monthReset").onclick=()=>{calDate=new Date();renderAttendance()};document.getElementById("prevMonth").onclick=()=>{calDate.setMonth(calDate.getMonth()-1);renderAttendance()};document.getElementById("nextMonth").onclick=()=>{calDate.setMonth(calDate.getMonth()+1);renderAttendance()};
}
function updateShift(){const night=data.profile.shift==="Night";document.getElementById("patrolBadge").textContent=night?"Patrol Enabled":"Patrol Disabled";document.getElementById("patrolBtn").disabled=!night}
let timerInt=null;
function punchIn(){if(data.punch.in)return toast("Already punched in");data.punch.in=new Date().toISOString();data.punch.last=data.punch.in;save();ensureToday("PRESENT");renderPunch();toast("Punch In recorded")}
function punchOut(){if(!data.punch.in)return toast("Punch In first");data.punch.out=new Date().toISOString();data.punch.last=data.punch.out;const k=todayKey();data.attendance[k]={status:"PRESENT",in:new Date(data.punch.in).toTimeString().slice(0,5),out:new Date(data.punch.out).toTimeString().slice(0,5),break:data.settings.break,note:"Auto"};save();renderPunch();toast("Punch Out recorded")}
function renderPunch(){const i=data.punch.in,o=data.punch.out;document.getElementById("lastPunch").textContent=data.punch.last?new Date(data.punch.last).toLocaleTimeString("en-IN",{hour:"2-digit",minute:"2-digit"}):"--:--";document.getElementById("dutyStatus").textContent=i&&!o?"Running":o?"Completed":"Ready";document.getElementById("statusText").textContent=i&&!o?"Punched In":o?"Duty Complete":"Not Punched";if(timerInt)clearInterval(timerInt);if(i&&!o){timerInt=setInterval(()=>{document.getElementById("dutyTimer").textContent=duration(new Date(i),new Date())},1000)}else document.getElementById("dutyTimer").textContent=i&&o?duration(new Date(i),new Date(o)):"00:00:00";document.getElementById("totalDuty").textContent=i&&o?duration(new Date(i),new Date(o)).slice(0,5):"00:00"}
function duration(a,b){let s=Math.max(0,Math.floor((b-a)/1000)),h=Math.floor(s/3600),m=Math.floor(s%3600/60),z=s%60;return [h,m,z].map((v,i)=>String(v).padStart(2,"0")).join(":")}
function ensureToday(status){const k=todayKey();data.attendance[k]=data.attendance[k]||{status,in:"",out:"",break:data.settings.break,note:""};data.attendance[k].status=status;save()}
let calDate=new Date();
const statusClass={PRESENT:"p",ABSENT:"a",LEAVE:"l",OFF:"o",HOLIDAY:"h",INCOMPLETE:"i"};
function renderAttendance(){const y=calDate.getFullYear(),m=calDate.getMonth();document.getElementById("monthTitle").textContent=calDate.toLocaleDateString("en-IN",{month:"long",year:"numeric"});const first=new Date(y,m,1).getDay(),days=new Date(y,m+1,0).getDate(), c=document.getElementById("calendar");c.innerHTML=["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map(x=>`<div class="cal-cell head">${x}</div>`).join("");for(let i=0;i<first;i++)c.innerHTML+=`<div class="cal-cell"></div>`;let counts={PRESENT:0,ABSENT:0,LEAVE:0,OFF:0,HOLIDAY:0,INCOMPLETE:0},hours=0,ot=0;for(let d=1;d<=days;d++){const k=`${y}-${String(m+1).padStart(2,"0")}-${String(d).padStart(2,"0")}`,a=data.attendance[k]||{},s=a.status||"";if(s)counts[s]=(counts[s]||0)+1;let wh=workHours(a);hours+=wh;ot+=Math.max(0,wh-data.settings.hours);c.innerHTML+=`<div class="cal-cell ${statusClass[s]||""} ${k===todayKey()?"today":""}" title="${s||"Not filed"}"><b>${d}</b>${s?statusShort(s):""}</div>`}document.getElementById("sumDays").textContent=days;document.getElementById("sumHours").textContent=hours.toFixed(2);document.getElementById("sumOT").textContent=ot.toFixed(2);document.getElementById("summaryRows").innerHTML=[["PRESENT","Present","p"],["ABSENT","Absent","a"],["LEAVE","Leave","l"],["OFF","Off","o"],["HOLIDAY","Holiday","h"],["INCOMPLETE","Incomplete","i"]].map(x=>`<p><span class="${x[2]}">${x[1]}</span><b>${counts[x[0]]||0}</b></p>`).join("");renderTable(y,m,days)}
function statusShort(s){return {PRESENT:"P",ABSENT:"A",LEAVE:"L",OFF:"O",HOLIDAY:"H",INCOMPLETE:"I"}[s]||""}
function workHours(a){if(!a?.in||!a?.out)return 0;let [ih,im]=a.in.split(":").map(Number),[oh,om]=a.out.split(":").map(Number);let mins=oh*60+om-(ih*60+im);if(mins<0)mins+=1440;mins-=Number(a.break||0);return Math.max(0,mins/60)}
function renderTable(y,m,days){const body=document.getElementById("attendanceBody");body.innerHTML="";for(let d=1;d<=days;d++){const k=`${y}-${String(m+1).padStart(2,"0")}-${String(d).padStart(2,"0")}`,a=data.attendance[k]||{status:"",in:"",out:"",break:data.settings.break,note:""};const day=new Date(y,m,d).toLocaleDateString("en-IN",{weekday:"short"});body.innerHTML+=`<tr><td>${fmtDate(new Date(y,m,d))}</td><td>${day}</td><td><select class="status-select" data-k="${k}" data-f="status"><option value="">—</option>${["PRESENT","ABSENT","LEAVE","OFF","HOLIDAY","INCOMPLETE"].map(s=>`<option ${a.status===s?"selected":""}>${s}</option>`).join("")}</select></td><td><input data-k="${k}" data-f="in" value="${a.in||""}" type="time"></td><td><input data-k="${k}" data-f="out" value="${a.out||""}" type="time"></td><td><input data-k="${k}" data-f="break" value="${a.break??data.settings.break}" type="number" min="0"></td><td>${workHours(a).toFixed(2)}</td><td>${Math.max(0,workHours(a)-data.settings.hours).toFixed(2)}</td><td><input data-k="${k}" data-f="note" value="${a.note||""}"></td></tr>`}body.querySelectorAll("[data-k]").forEach(el=>el.onchange=()=>{const k=el.dataset.k,f=el.dataset.f;data.attendance[k]=data.attendance[k]||{status:"",in:"",out:"",break:data.settings.break,note:""};data.attendance[k][f]=el.value;save();renderAttendance()})}
function renderSalary(){const p=data.profile,y=calDate.getFullYear(),m=calDate.getMonth(),days=new Date(y,m+1,0).getDate();let present=0,absent=0,leave=0,off=0,hours=0,ot=0;for(let d=1;d<=days;d++){const k=`${y}-${String(m+1).padStart(2,"0")}-${String(d).padStart(2,"0")}`,a=data.attendance[k]||{};if(a.status==="PRESENT")present++;if(a.status==="ABSENT")absent++;if(a.status==="LEAVE")leave++;if(a.status==="OFF"||a.status==="HOLIDAY")off++;hours+=workHours(a);ot+=Math.max(0,workHours(a)-data.settings.hours)}const sal=+p.salary||0,basic=sal*.5,hra=sal*.3,other=sal*.2,otAmt=sal/26/data.settings.hours*ot,gross=basic+hra+other+otAmt,pf=basic*.12,esi=gross*.0075,net=gross-pf-esi;document.getElementById("salaryMonth").textContent=calDate.toLocaleDateString("en-IN",{month:"long",year:"numeric"});document.getElementById("workerId").textContent=p.id||"SG001";setHTML("personalDetails",[["Employee ID",p.id],["Name",p.name],["Joining Date",p.join],["Designation",p.designation],["Duty Site",p.site],["Bank Account",p.account],["IFSC",p.ifsc],["Monthly Salary",money(sal)]]);setHTML("workingDetails",[["Total Days",days],["Present Days",present],["Absent Days",absent],["Leave Days",leave],["Off / Holiday",off],["Worked Hours",hours.toFixed(2)],["OT Hours",ot.toFixed(2)]]);setHTML("earnings",[["Basic (50%)",money(basic)],["HRA (30%)",money(hra)],["Other Allowance (20%)",money(other)],["OT Amount",money(otAmt)],["Gross Earnings",money(gross)]]);setHTML("deductions",[["EPF (12% on Basic)",money(pf)],["ESI (0.75% on Gross)",money(esi)],["Other Deduction",money(0)],["Total Deduction",money(pf+esi)]]);setHTML("employer",[["EPF (12%)",money(pf)],["ESI (3.25%)",money(gross*.0325)],["CTC (Approx.)",money(gross+pf+gross*.0325)]]);document.getElementById("netSalary").textContent=money(net);document.getElementById("amountWords").textContent=numberWords(Math.round(net))+" Rupees Only"}
function setHTML(id,arr){document.getElementById(id).innerHTML=arr.map(x=>`<p><span>${x[0]}</span><b>${x[1]??""}</b></p>`).join("")}
function numberWords(n){if(!n)return"Zero";const o=["","One","Two","Three","Four","Five","Six","Seven","Eight","Nine","Ten","Eleven","Twelve","Thirteen","Fourteen","Fifteen","Sixteen","Seventeen","Eighteen","Nineteen"],t=["","","Twenty","Thirty","Forty","Fifty","Sixty","Seventy","Eighty","Ninety"];function f(x){if(x<20)return o[x];if(x<100)return t[Math.floor(x/10)]+(x%10?" "+o[x%10]:"");if(x<1000)return o[Math.floor(x/100)]+" Hundred"+(x%100?" "+f(x%100):"");if(x<100000)return f(Math.floor(x/1000))+" Thousand"+(x%1000?" "+f(x%1000):"");if(x<10000000)return f(Math.floor(x/100000))+" Lakh"+(x%100000?" "+f(x%100000):"");return f(Math.floor(x/10000000))+" Crore"+(x%10000000?" "+f(x%10000000):"")}return f(n)}
function renderProfile(){const p=data.profile;const map={pName:"name",pId:"id",pDob:"dob",pMobile:"mobile",pAddress:"address",pBank:"bank",pAccount:"account",pIfsc:"ifsc",pHolder:"holder",pJoin:"join",pDesignation:"designation",pSite:"site",pShift:"shift",pSalary:"salary"};Object.entries(map).forEach(([id,k])=>document.getElementById(id).value=p[k]??"")}
function saveProfile(){const p=data.profile;const map={pName:"name",pId:"id",pDob:"dob",pMobile:"mobile",pAddress:"address",pBank:"bank",pAccount:"account",pIfsc:"ifsc",pHolder:"holder",pJoin:"join",pDesignation:"designation",pSite:"site",pShift:"shift",pSalary:"salary"};Object.entries(map).forEach(([id,k])=>p[k]=document.getElementById(id).value);save();updateShift();toast("Profile saved");renderSalary()}
function renderSettings(){document.getElementById("sHours").value=data.settings.hours;document.getElementById("sAuto").value=data.settings.auto;document.getElementById("sBreak").value=data.settings.break;["sHours","sAuto","sBreak"].forEach((id,i)=>document.getElementById(id).onchange=e=>{data.settings[["hours","auto","break"][i]]=+e.target.value||0;save();renderAttendance()})}
function renderPatrol(){document.getElementById("roundName").value=data.round.name;document.getElementById("roundTarget").value=data.round.target;document.getElementById("roundTitle").textContent=data.round.name;document.getElementById("roundProgressText").textContent=`${data.round.done} / ${data.round.target}`;document.getElementById("roundProgress").style.width=Math.min(100,data.round.done/data.round.target*100)+"%";document.getElementById("roundCount").textContent=`${data.round.done} / ${data.round.target}`}
function reportString(){const p=data.profile,k=todayKey(),a=data.attendance[k]||{};return `SSG - SECURITY GUARD DAILY REPORT\nDate: ${fmtDate(new Date())}\nName: ${p.name||"Security Guard"}\nEmployee ID: ${p.id}\nDuty Site: ${p.site}\nShift: ${p.shift}\nStatus: ${a.status||"NOT FILED"}\nPunch In: ${a.in||"--:--"}\nPunch Out: ${a.out||"--:--"}\nWork Hours: ${workHours(a).toFixed(2)}\nPatrol Rounds: ${data.round.done}/${data.round.target}\n\nGate Check: Completed\nVisitor Entry: Completed\nArea Monitoring: Completed\n\nSSG • Simple • Smart • Complete`}
function renderReport(){document.getElementById("reportText").value=reportString();document.getElementById("reportPreview").textContent=reportString()}
function exportData(){const blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="SSG-backup.json";a.click();URL.revokeObjectURL(a.href);toast("Backup exported")}
function importData(e){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{data=JSON.parse(r.result);save();location.reload()}catch{toast("Invalid backup file")}};r.readAsText(f)}
document.addEventListener("DOMContentLoaded",init);